### PR TITLE
Adding cli commands for servo setup

### PR DESCRIPTION
**Pull request by schugabe**
This commit makes the servo setup via cli commands possible and adds the servo config to the dump command.

### CODE REVIEW

**Comment by fiendie** [comment]
@schugabe Is this still relevant?

**Comment by schugabe** [comment]
@fiendie yes it is still relevant. I guess the "coding style violation" is the long if condition. Should this condition be in one line or what is the preferred style here?

**Comment by fiendie** [comment]
Looks like a line ending fuck-up again :/

**Comment by schugabe** [comment]
I installed astyle now. The problem were spaces in empty lines/at the end of lines.

**Comment by fiendie** [comment]
@trollcop Merge please

**Pull request merged**
