### PR TITLE
Two new PID controllers (MultiWii 2.3 and Harakiri)

### PR DESCRIPTION
**Pull request by MJ666**
During the work on the AlienWii32 FC we added two new PID controllers which both perform better then the ones included in BF for our Nanocopters. They will improve yaw behavior. There are many pilots of larger gear which are also quite satisfied with them. They will be activated in CLI with set pid_controller = "X". X will be 2 for the MultiWii 2.3 and 3 for the Harakiri PID controller. They are already flight tested for a couple of days on AlienWii based Nanocopters. An compiled hex for the NAZE can be found here:

https://github.com/AlienWiiBF/baseflight/tree/AlienWii32/obj

@trollcop I leave it up to you if you are interested to merge this. May be some more BF pilots are interested in this.

### CODE REVIEW

**Comment by trollcop** [comment]
With this kinda indentation/code quality? Good luck.

**Comment by MJ666** [comment]
@trollcop Don't understand? If you are more specific and interested to merge I can make the required changes.

**Comment by trollcop** [comment]
1) remove alienwii stuff as that will never be merged due to DCL
2) read CodingStyle, if you don't see what's wrong then read it again until
you do.
3) Benefit of either PID controller is unclear anyway, there are no docs,
default PIDs, etc, it will be just as useful as the current pidRewrite one
that noone actually uses.

**Comment by schugabe** [comment]
I use the current "pidRewrite" controller and it is great!

**Comment by trollcop** [comment]
Cool, have you considered wrigin some docs on the wiki, with good ballpark
default settings and such? :)

**Comment by schugabe** [comment]
Actually I planed to do something like that for some time ... but I never hat enough time. Maybe in the near future :smiley:

**Comment by trollcop** [comment]
Exactly, seems to be the thing people with jobs + lives usually use as
excuse.

**Comment by schugabe** [comment]
Since the multiwii 2.3 controller fixes an issue of the 2.2 controller I think it is unnecessary to introduce a new alternative controller. Just add the changes to the default controller. Or would this break some pid settings?

**Comment by trollcop** [comment]
It shouldn't, and I thought i already merged 2.3 changes anyway.
minus the dumb optimization shit they added to make it unreadable

**Comment by MJ666** [comment]
@trollcop 

1)	Your statement is clear. We have discussed this already in the past but this is a complete different topic. 
2)	I did this already a couple of times, may be I’m blind and have overseen something. Sorry.
3)	In difference to the pidRewrite both PID controllers will work quite well with the actual default settings as a starting point. BF is still using the PID controller algorithm used with MultiWii 2.2 and before. MultiWii 2.3 is an direct port of the actual MultiWii code. In general there is a tendency to end up with slightly lower P value for roll and pitch then with the default PID controller after fine tuning. Same as moving from MultiWii 2.2 to 2.3. Many pilots have enjoyed this improvement as a major step. Harakiri is an improved version ported from the Harakiri firmware which is using more floating point math and an slightly improved algorithm.

I agree that usually one well working PID controller should do it. Looks to be it is not this easy and there are different preferences. Fell free to give it a try and get your own impression.

If you think BF is fine with the existing PID controllers and there is no improvement needed we can close this PR. I easily can continue to maintain my fork with the things we need for the AlienWii32 FC. As you know there is an alternative but our intention is to give users the freedom to choose between the alternatives.

**Comment by fiendie** [comment]
Can we close this? There doesn't seem to be much interest in merging all of that stuff in one big lump anyway.

**Comment by MJ666** [comment]
Ok, let's close this PR. It looks like the final AlienWii32 will be based on STM32F3 anyhow and there are only a few F1 based AlienWii32 FC's out in the field. I still will maintain my development fork as needed. If there is no interest on the improved PID controller the is no value to keep this PR open.

**Comment by fiendie** [comment]
@MJ666: I meant you could try to submit individual features in individual pull requests. Dunno about @trollcop, I don't have anything against additional PID controllers but he already stated that he won't merge the AlienWii stuff. So if we could untangle it a bit it might get merged.

**Comment by trollcop** [comment]
Because brushed shit needs all the power of F3.

**Comment by MJ666** [comment]
Very polite as always. You know how to make good friends. You are wondering why BF has now multiple independent fork's. May be this is one of the reasons. Have fun.

BTW: The F3 is not really much more expensive the F1 and is saving additional USB components and space. There may be other reason why people do things differently as you may initially think.

**Comment by trollcop** [comment]
you're just angry I didn't want your shitty clone in my codebase, and
Clifton will accept anything, so you ran crying there :)

nothing in cloneflight is innovative, it's either code copied without
understanding (pretty much everything) or stuff plagiarized from somewhere
without giving credit (pt1 from brm, 2811 leds from me, etc). the rest is
mindless renaming of shit to confuse users.

enjoy your short-lived commercial success - maybe one day you will have
software that will make use of full f3 on a brushed motor tinyquad.

it won't be written by copypaste Clifton tho :)

**Pull request closed without merging**
