### PR TITLE
Blackbox logger (thenickdudes)

### PR DESCRIPTION
**Pull request by readerror67**
Brought things up to sync fumbling through git, builds in Keil now with lame_printf.

Long shot PR but hey might as well.

### CODE REVIEW

**Comment by readerror67** [comment]
build it bitch

**Comment by treymarc** [comment]
hum.. i dont think that one want to merge the README.md back into baseflight ? or else ?

**Comment by treymarc** [comment]
also many commits , would be better if only one commit with the inclusion of original author name :)

**Comment by fiendie** [comment]
ok to test

**Comment by trollcop** [comment]
not going to happen

**Pull request closed without merging**
