### PR TITLE
Added UBX-CFG-NAV5 (0x06 0x24) message to UBLOX initialization.

### PR DESCRIPTION
**Pull request by jaahaavi**
- GPS dynamic platform model is set to pedestrian.

### CODE REVIEW

**Comment by jaahaavi** [comment]
GPS flagging change made and it seems that now CJMCU-build is working again.

**Comment by ezikiel12** [comment]
Setting to pedestrain is very bad for planes. It has a speed limit of 67mph, and I have confirmed on my flying wing that it goes completely insane at 67-70mph

**Comment by jaahaavi** [comment]
Doesn't GPS get sync back immediately after plane slows down? I also assume that your plane doesn't fly over 67mph when return to home/waypoint mode is activated?

I changed mode from automotive to pedestrian because GPS deviation in pedestrian mode is so much smaller. For example when you activate GPS HOLD position, it will make huge different if your quad keeps in 6*6 meter area (+-3 meters pedestrian deviation) versus 30*30 meter area (+-15 meters automotive deviation).

**Comment by ezikiel12** [comment]
Yes it does regain sat fix when I slow down. But pedestrian is also 100% confirmed to lose SATs constantly in banking turns and such. I tested this thoroughly over the weekend. Pedestrian is garbage compared to airborne 1G for fixed wing aircraft. With airborne I have solid 10+ SATs constant. With pedestrian its all over the place consistently losing fix, even under 67mph. This is not just me, fellow flying buddies have tested this now and we are 100% certain pedestrian mode is garbage. Great for hovering in one spot I'm sure, but not if you just need a solid fix for getting you home in a sketchy situation.

**Comment by jaahaavi** [comment]
Both of those modes have their pros and cons. Airborne 1G max deviation is crap in multicopters because multicopter can wander over 50 meters a way from point where it should be, but it's accuracy is enough for bringing back a plane that is going out of sight. Also that pedestrian mode accuracy doesn't come cheap. GPS is working best when it's kept in same level and tilting affects the position calculations. In pedestrian mode GPS is calculating continuous strict position and sudden banking turns/barrel rolls makes satellite positions to change and it takes some time (depends on gps) to solve the current strict position. On the other hand airborne 1G doesn't have any velocity sanity checks and it's updating positions are not so strict so it can report positions even they aren't so accurate.

I see that this is a problem for fixed wing guys. Perhaps that UBLOX initialization should be so that it would be pedestrian mode when multicopter is selected and airborne 1G mode when fixed wing is selected.

By the way. Is that return to home not working when losing the fix, or how does it affect? Does it level the plane first and slow down and then return it home?  I don't know how fixed wing code works (haven't been interested on that code because I don't have planes any more).

**Comment by ezikiel12** [comment]
Right. PatrickE did me up a custom build that does exactly this.

Over 67mph rth will not work at all because it jumps to 0 satellites over and over. In banks and turns it drops out too often to be able to trust rth.

**Comment by kh4** [comment]
I wonder how well it would work when changed dynamically, i.e. switch to pedestrian when moving slower than 20mph and switch to car mode when >40mph.

**Pull request merged**
